In [1]:
#importing needed packages
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from src.data_cleaning import prepare_data

In [5]:
original_data = pd.read_csv('../data/german_credit_data.csv')
#reading the dataset
data = prepare_data('../data/german_credit_data.csv')
#checking first rows
data.head()

,age,sex,job,housing,saving_accounts,checking_account,credit_amount,duration,purpose,risk
0,67,male,2,own,NaN,little,1169,6,radio/tv,good
1,22,female,2,own,little,moderate,5951,48,radio/tv,bad
2,49,male,1,own,little,NaN,2096,12,education,good
3,45,male,2,free,little,little,7882,42,furniture/equipment,good
4,53,male,2,free,little,little,4870,24,car,bad

In [3]:
#checking data structure
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               1000 non-null   int64
 1   sex               1000 non-null   object
 2   job               1000 non-null   int64
 3   housing           1000 non-null   object
 4   saving_accounts   817 non-null    object
 5   checking_account  606 non-null    object
 6   credit_amount     1000 non-null   int64
 7   duration          1000 non-null   int64
 8   purpose           1000 non-null   object
 9   risk              1000 non-null   object
dtypes: int64(4), object(6)
memory usage: 85.9+ KB

In [4]:
#summary statistics
data.describe()

               age          job  credit_amount     duration
count  1000.000000  1000.000000    1000.000000  1000.000000
mean     35.546000     1.904000    3271.258000    20.903000
std      11.375469     0.653614    2822.736876    12.058814
min      19.000000     0.000000     250.000000     4.000000
25%      27.000000     2.000000    1365.500000    12.000000
50%      33.000000     2.000000    2319.500000    18.000000
75%      42.000000     2.000000    3972.250000    24.000000
max      75.000000     3.000000   18424.000000    72.000000